# plugins

## list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_date_icon ' '
set -g @tmux_power_time_icon ' '
set -g @tmux_power_user_icon ' '
set -g @tmux_power_session_icon ' '
set -g @tmux_power_theme 'snow'
set -g @tmux_power_time_format '%H:%M'
set -g @tmux_power_show_host false

# init tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'

# ---
# rebindings

## ctrl+[left|right] working
set-window-option -g xterm-keys on

## split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

## bind key (BK) ctrl+b -> ctrl+a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# ---
# mouse

## mouse ON on default
set -g mouse off

## BK+M will toggle mouse on
bind-key M \
  set-option -g mouse on \;\
  display-message 'Mouse: ON'

## BK+m will toggle mouse off
bind-key m \
  set-option -g mouse off \;\
  display-message 'Mouse: OFF'

# ---
# etc

## for text copying
setw -g mode-keys vi
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi v send -X begin-selection

## disable monitor-activity alerts
set -g monitor-activity off
set -g visual-activity off

## fix macOS GUI services (pbcopy, notifications, Keychain) inside tmux
set -g default-command "reattach-to-user-namespace -l ${SHELL}"

## open new windows in the same directory
bind c new-window -c "#{pane_current_path}"

## optional: open new panes in the same directory too
bind '-' split-window -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"
